accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
    )

from .views import (
    RegisterView,
    activate_user_view,
    UserLoginView,
    UserLogoutView,
    UserChangePasswordView,
    UserProfileView,
    ProfileUpdateView,
    ProfileDeleteView,
    )

urlpatterns = [
    url(r'^activate/(?P<code>[a-zA-Z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^register/', RegisterView.as_view(), name='register'),


    url(r'^login/$', UserLoginView.as_view(), name='login'),
    url(r'^logout/$', UserLogoutView.as_view(), name='logout'),

    url(r'^change_password/$', UserChangePasswordView.as_view(), name='change_password'),

    url(r'^profile/$', UserProfileView.as_view(), name='profile'),
    url(r'^profile/update/(?P<pk>\d+)/$', ProfileUpdateView.as_view(), name='update'),
    url(r'^profile/delete/$', ProfileDeleteView.as_view(), name='delete'),


    url(r'^reset_password/$', password_reset, {
        'template_name': 'accounts/reset_password.html',
        'post_reset_redirect': 'accounts:password_reset_done',
        'email_template_name': 'accounts/reset_password_email.html',
        }, name='password_reset'),

    url(r'^reset_password/done/$', password_reset_done,
        {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'post_reset_redirect': 'accounts:password_reset_complete',
         'template_name': 'accounts/reset_password_confirm.html',
         }, name='password_reset_confirm'),

    url(r'^reset_password/complete/$', password_reset_complete,
        {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),
]

e_commerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from products.urls import ProductsListView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^contact_us/', include('contact_us.urls', namespace='contact_us')),
    url(r'^$', ProductsListView.as_view(), name='main_home'),


    url(r'^api/accounts/', include('accounts.api.urls', namespace='accounts_api')),
    url(r'^api/products/', include('products.api.urls', namespace='products_api')),
    url(r'^api/orders/', include('orders.api.urls', namespace='orders_api')),
    url(r'^api/reviews/', include('reviews.api.urls', namespace='reviews_api')),
    url(r'^api/contact_us/', include('contact_us.api.urls', namespace='contact_us_api')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/api/urls.py
from django.conf.urls import url
from .views import (
    AddToCartAPIView,
    CartAPIView,
    OrderUpdateAPIView,
    OrderDeleteAPIView,
    PendingOrdersAPIView,
    AcceptedOrdersAPIView,
    RejectedOrdersAPIView,
    BuyOrdersAPIView,
)

urlpatterns = [
    url(r'^order/(?P<id>\d+)/$', AddToCartAPIView.as_view(), name='order_api'),
    url(r'^order/(?P<id>\d+)/update/$', OrderUpdateAPIView.as_view(), name='update_api'),
    url(r'^order/(?P<id>\d+)/delete/$', OrderDeleteAPIView.as_view(), name='delete_api'),
    url(r'^cart/$', CartAPIView.as_view(), name='cart_api'),
    url(r'^pending/$', PendingOrdersAPIView.as_view(), name='pending_api'),
    url(r'^rejected/$', RejectedOrdersAPIView.as_view(), name='rejected_api'),
    url(r'^accepted/$', AcceptedOrdersAPIView.as_view(), name='accepted_api'),
    url(r'^buy/$', BuyOrdersAPIView.as_view(), name='buy_api'),
]

orders/urls.py
from django.conf.urls import url

from .views import (
    CheckoutView,
    CheckoutUpdateView,
    OrderDeleteView,
    CheckoutOrderView,
    OrdersView,
    AcceptedOrdersView,
    RejectedOrdersView,
    BuyOrdersView,
    BuyThankView,
    )

urlpatterns = [
    url(r'^order/(?P<id>\d+)/$', CheckoutView.as_view(), name='order'),
    url(r'^order/(?P<pk>\d+)/update/$', CheckoutUpdateView.as_view(), name='update'),
    url(r'^order/(?P<id>\d+)/delete/$', OrderDeleteView.as_view(), name='delete'),
    url(r'^cart/$', CheckoutOrderView.as_view(), name='checkout'),
    url(r'^pending/$', OrdersView.as_view(), name='pending'),
    url(r'^rejected/$', RejectedOrdersView.as_view(), name='rejected'),
    url(r'^accepted/$', AcceptedOrdersView.as_view(), name='accepted'),
    url(r'^thank_you/$', BuyThankView.as_view(), name='thank'),
    url(r'^buy/$', BuyOrdersView.as_view(), name='buy'),
]

orders/forms.py
from django import forms

from .models import Checkout
from products.models import Product


class UpdateCheckoutForm(forms.ModelForm):
    product_id = forms.IntegerField(widget=forms.HiddenInput)

    class Meta:
        model = Checkout
        fields = [
            'product_id',
            'quantity',
        ]

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        qs = self.cleaned_data['product_id']
        available = Product.objects.filter(id=qs).first().quantity
        if quantity > available:
            raise forms.ValidationError('Quantity more than the available quantity = {}!'.format(available))
        if quantity == 0:
            raise forms.ValidationError('Quantity can not be less than 1')
        return quantity

orders/api/views.py
from rest_framework.generics import (
    RetrieveUpdateAPIView,
    DestroyAPIView,
    ListAPIView,
)

from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated

from .serializers import (
    OrdersSerializer,
    CartSerializer,
    OrderUpdateSerializer,
)
from accounts.models import Account
from products.models import Product
from orders.models import Checkout
from .permissions import IsOwnerOrReadOnly


class AddToCartAPIView(APIView):
    permission_classes = [IsAuthenticatedOrReadOnly, IsAuthenticated]

    def post(self, request, id):
        user = self.request.user
        if user.is_authenticated():
            qs = Checkout.objects.filter(product_id=id, user=user, status='waiting')
            if qs.exists():
                return Response({'message': ['already exists!']}, status=HTTP_200_OK)
            else:
                product = Product.objects.filter(id=id, publish=True).first()
                checkout = Checkout.objects.create(
                    user=self.request.user,
                    product_id=id,
                    name=product.name,
                    slug=product.slug,
                    price=product.price,
                    quantity=1,
                    discount=product.discount,
                    image=product.image,
                )
                return Response({'message': ['added successfully!']}, status=HTTP_200_OK)
        else:
            return Response({'message': ['you must be logged in first!']}, status=HTTP_200_OK)


class CartAPIView(ListAPIView):
    serializer_class = CartSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsAuthenticated]

    def get_queryset(self, *args, **kwargs):
        queryset = Checkout.objects.filter(user=self.request.user, status='waiting').order_by('-id')
        return queryset


class PendingOrdersAPIView(ListAPIView):
    serializer_class = OrdersSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsAuthenticated]

    def get_queryset(self, *args, **kwargs):
        queryset = Checkout.objects.filter(user=self.request.user, status='pending').order_by('-id')
        return queryset


class AcceptedOrdersAPIView(ListAPIView):
    serializer_class = OrdersSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsAuthenticated]

    def get_queryset(self, *args, **kwargs):
        queryset = Checkout.objects.filter(user=self.request.user, status='accepted').order_by('-id')
        return queryset


class RejectedOrdersAPIView(ListAPIView):
    serializer_class = OrdersSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsAuthenticated]

    def get_queryset(self, *args, **kwargs):
        queryset = Checkout.objects.filter(user=self.request.user, status='rejected').order_by('-id')
        return queryset


class OrderUpdateAPIView(RetrieveUpdateAPIView):
    serializer_class = OrderUpdateSerializer
    lookup_field = 'id'
    lookup_url_kwarg = 'id'
    permission_classes = [IsOwnerOrReadOnly, IsAuthenticated]

    def get_queryset(self, *args, **kwargs):
        queryset = Checkout.objects.filter(user=self.request.user, status='waiting').order_by('-id')
        return queryset


class OrderDeleteAPIView(DestroyAPIView):
    serializer_class = OrdersSerializer
    lookup_field = 'id'
    permission_classes = [IsOwnerOrReadOnly, IsAuthenticated]

    def get_queryset(self, *args, **kwargs):
        queryset = Checkout.objects.filter(user=self.request.user, status='waiting', id=self.kwargs['id']).order_by('-id')
        return queryset


class BuyOrdersAPIView(APIView):
    lookup_field = 'id'
    permission_classes = [IsOwnerOrReadOnly, IsAuthenticated]

    def post(self, request):
        username = self.request.user
        if username is None:
            raise Response({'message': ['you have not the permission to do that!']}, status=HTTP_400_BAD_REQUEST)
        else:
            account = Account.objects.filter(user=username)
            qs = Checkout.objects.filter(user=username, status='waiting')
            if account.exists():
                user = account.first()
                if user.gender is None \
                or user.country is None \
                or user.region is None \
                or user.address1 is None \
                or user.phone_number1 is None \
                or user.phone_number2 is None:
                    return Response(
                        {'message': ['add your information first to complete buy orders!']},
                        status=HTTP_200_OK
                    )
            if qs.exists():
                for order in qs:
                    order.status = 'pending'
                    order.save()
                    product = Product.objects.filter(id=order.product_id).first()
                    product.quantity -= order.quantity
                    product.number_of_sales += 1
                    product.save()
                return Response(
                        {'message': ['thank you for buying orders!']},
                        status=HTTP_200_OK
                    )

orders/views.py
from django.shortcuts import redirect, get_object_or_404, render_to_response
from django.views.generic import View, ListView, TemplateView
from django.contrib import messages
from django.http import Http404
from django.template import RequestContext

from .models import Checkout
from products.models import Product
from accounts.models import Account


# add to cart form
class CheckoutView(View):
    template_name = 'orders/checkout.html'

    def post(self, request, id):
        id = self.kwargs['id']
        qs = Checkout.objects.filter(product_id=id, status='waiting')
        if qs.exists():
            messages.success(request, 'You can not add this product because its already added before!')
            return redirect('orders:checkout')
        else:
            product = get_object_or_404(Product, id=id, publish=True)
            checkout = Checkout.objects.create(
                user=self.request.user,
                product_id=id,
                name=product.name,
                slug=product.slug,
                price=product.price,
                quantity=1,
                discount=product.discount,
                image=product.image,
            )
            messages.success(request, 'Successfully Added!')
            return redirect('orders:checkout')


# all orders page that submitted
class OrdersView(ListView):
    template_name = 'orders/orders.html'
    queryset = ''

    def get_context_data(self, **kwargs):
        context = super(OrdersView, self).get_context_data(**kwargs)
        context['title'] = 'Pending Orders'
        if self.request.user.is_authenticated:
            context['orders'] = Checkout.objects.filter(user=self.request.user, status='pending')
        else:
            raise Http404
        return context


# all orders page that submitted & accepted
class AcceptedOrdersView(ListView):
    template_name = 'orders/orders.html'
    queryset = ''

    def get_context_data(self, **kwargs):
        context = super(AcceptedOrdersView, self).get_context_data(**kwargs)
        context['title'] = 'Accepted Orders'
        if self.request.user.is_authenticated:
            context['orders'] = Checkout.objects.filter(user=self.request.user, status='accepted')
        else:
            raise Http404
        return context


# all orders page that submitted & rejected
class RejectedOrdersView(ListView):
    template_name = 'orders/orders.html'
    queryset = ''

    def get_context_data(self, **kwargs):
        context = super(RejectedOrdersView, self).get_context_data(**kwargs)
        context['title'] = 'Rejected Orders'
        if self.request.user.is_authenticated:
            context['orders'] = Checkout.objects.filter(user=self.request.user, status='rejected')
        else:
            raise Http404
        return context


# checkout page
class CheckoutOrderView(ListView):
    template_name = 'orders/checkout.html'
    queryset = ''

    def get_context_data(self, **kwargs):
        context = super(CheckoutOrderView, self).get_context_data(**kwargs)
        context['title'] = 'Cart'
        if self.request.user.is_authenticated:
            qs = Checkout.objects.filter(user=self.request.user, status='waiting')
            context['orders'] = qs
            orders = qs
            total = 0
            for order in orders:
                total += order.price * order.quantity
            context['total'] = total
        else:
            raise Http404
        return context


# update order page
class CheckoutUpdateView(View):
    template_name = 'orders/checkout.html'

    def post(self, request, pk):
        quantity = int(request.POST['quantity'])
        product_id = request.POST['product_id']
        available = Product.objects.filter(id=product_id).first()
        if quantity > available.quantity:
            messages.success(request, 'Quantity more than the available quantity : {} for product : {}'.format(available.quantity, available.name))
            return redirect('orders:checkout')
        if quantity == 0 or quantity < 0:
            messages.success(request, 'Quantity can not be less than 1 for product : {}'.format(available.name))
            return redirect('orders:checkout')
        qs = Checkout.objects.filter(id=pk, status='waiting')
        if qs.exists() and qs.count() == 1:
            product_quantity = qs.first()
            product_quantity.quantity = quantity
            product_quantity.save()
            messages.success(request, 'Successfully Added!')
            return redirect('orders:checkout')


# delete order
class OrderDeleteView(View):
    template_name = 'orders/checkout.html'

    def post(self, request, id):
        username = self.request.user
        if username is None:
            raise Http404
        else:
            qs = Checkout.objects.filter(id=id)
            if qs.exists() and qs.count() == 1:
                order = qs.first()
                order.delete()
                return redirect('orders:checkout')


# Buy orders
class BuyOrdersView(View):
    template_name = 'orders/orders.html'

    def post(self, request):
        username = self.request.user
        if username is None:
            raise Http404
        else:
            user_id = Account.objects.filter(user=username).first()
            account = Account.objects.filter(user=username)
            qs = Checkout.objects.filter(user=username, status='waiting')
            if account.exists():
                user = account.first()
                if user.gender is None \
                or user.country is None \
                or user.region is None \
                or user.address1 is None \
                or user.phone_number1 is None \
                or user.phone_number2 is None:
                    messages.success(request, 'add your information first to complete buy orders!')
                    return redirect('accounts:update', pk=user_id.id)
            if qs.exists():
                for order in qs:
                    order.status = 'pending'
                    order.save()
                    product = Product.objects.filter(id=order.product_id).first()
                    product.quantity -= order.quantity
                    product.number_of_sales += 1
                    product.save()
                return redirect('orders:thank')


class BuyThankView(TemplateView):
    template_name = "orders/thank.html"

    def get_context_data(self, **kwargs):
        context = super(BuyThankView, self).get_context_data(**kwargs)
        context['title'] = 'Thank You'
        return context


def handler404(request):
    response = render_to_response('404.html', {}, context_instance=RequestContext(request))
    response.status_code = 404
    return response

orders/templates/orders/checkout.html
{% extends 'base.html' %}

{% load static %}

{% load mathfilters %}

{% block title %}
    {{ user }}'s {{ title }} | {{ block.super }}
{% endblock %}

{% block body %}

    <br>
    <h3 class="text-center">{{ user }}'s {{ title }}</h3>
    <br>
    <br>
    <br>
    {% if orders %}
    <table class="table table-striped">
        <thead>
          <tr>
            <th>Picture</th>
            <th>Product Name</th>
            <th>Status</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Discount</th>
            <th>Total</th>
            <th>Order Updated</th>
            <th>Order Date</th>
            <th>Edit Quantity</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
        {% for order in orders %}
          <tr>
            <td><a href="{{ order.image.url }}"><img src="{{ order.image.url }}" style="max-height: 35px; max-width: 35px; border-radius: 10%;"></a></td>
            <td><a href="{{ order.get_absolute_url }}">{{ order.name }}</a></td>
            <td>{{ order.status }}</td>
            <td>{{ order.quantity }}</td>
            <td>{{ order.price }}</td>
            <td>{{ order.discount }}</td>
            <td>{{ order.price |mul:order.discount |div:100 |sub:order.price |mul:-1 |mul:order.quantity }}</td>
{#                            <td>{{ (order.price - order.discount) * order.quantity }}</td>#}
            <td>{{ order.updated | timesince }}</td>
            <td>{{ order.added | timesince }}</td>
{#            <td><a href="{% url 'orders:update' pk=order.id %}" class="btn btn-success">Edit</a></td>#}
            <td>
                <div class="update_quantity_button">
                    <button type="button" class="btn btn-success">Edit</button>
                </div>
                <div class="update_quantity" style="display: none;">
                <form method="POST" action="{% url 'orders:update' pk=order.id %}" class="form-group">
                    {% csrf_token %}
                    <input type="number" name="quantity" value="{{ order.quantity }}" class="form-control" style="display: inline-block; max-width: 80px; max-height: 33px;">
                    <input type="hidden" name="product_id" value="{{ order.product_id }}">
                    <button type="submit" class="btn btn-success save">Save</button>
                </form>
                </div>
            </td>
            <td>
                <a href="" data-toggle="modal" class="btn btn-danger" data-target="#delete_order{{ order.id }}">
                    Delete
                </a>
                {% include 'orders/delete_order_modal.html' %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      <br>
      <br>
      {% if request.user.is_authenticated %}
          {% if orders %}
            <a href="" data-toggle="modal" class="btn btn-success" data-target="#confirm_buy" style="display: table; margin: 0 auto;">
                <i class="fa fa-shopping-cart"></i>&emsp;Buy
            </a>
          {% endif %}
        {% include 'orders/cofirm_buy_modal.html' %}
      {% endif %}
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      {% else %}
        <h3 class="text-center">You have not {{ title }} orders yet!</h3>
      {% endif %}

{% endblock %}

orders/templates/orders/cofirm_buy_modal.html
<!-- Modal -->
<div class="modal fade" id="confirm_buy" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="border-radius: 6px;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Confirm Buy</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: -21px;">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to confirm buy {{ orders | length }} orders
        <br>
        With total price = {{ total }} &#036; ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form method="post" action="{% url 'orders:buy' %}" style="display: inline-block;">
            {% csrf_token %}
                <button class="btn btn-success">
                    Confirm Buy
                </button>
        </form>
      </div>
    </div>
  </div>
</div>

orders/templates/orders/delete_order_modal.html
<!-- Modal -->
<div class="modal fade" id="delete_order{{ order.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="border-radius: 6px;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Order</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: -21px;">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete order {{ order.name }} ?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form method="post" action="{% url 'orders:delete' id=order.id %}" style="display: inline-block;">
            {% csrf_token %}
                <button class="btn btn-danger">
                    Confirm Delete
                </button>
        </form>
      </div>
    </div>
  </div>
</div>

orders/templates/orders/orders.html
{% extends 'base.html' %}

{% load static %}

{% load mathfilters %}

{% block title %}
    {{ user }}'s {{ title }} | {{ block.super }}
{% endblock %}

{% block body %}

    <br>
    <h3 class="text-center">{{ user }}'s {{ title }}</h3>
    <br>
    <br>
    <br>
    {% if orders %}
    <table class="table table-striped">
        <thead>
          <tr>
            <th>Product Name</th>
            <th>Status</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Discount</th>
            <th>Total</th>
            <th>Order Updated</th>
            <th>Order Date</th>
          </tr>
        </thead>
        <tbody>
        {% for order in orders %}
          <tr>
            <td>{{ order.name }}</td>
            <td>{{ order.status }}</td>
            <td>{{ order.quantity }}</td>
            <td>{{ order.price }}</td>
            <td>{{ order.discount }}</td>
            <td>{{ order.price |mul:order.discount |div:100 |sub:order.price |mul:-1 |mul:order.quantity }}</td>
{#                            <td>{{ (order.price - order.discount) * order.quantity }}</td>#}
            <td>{{ order.updated | timesince }}</td>
            <td>{{ order.added | timesince }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
    {% else %}
        <h3 class="text-center">You have not {{ title }} yet!</h3>
    {% endif %}

{% endblock %}

orders/templates/orders/thank.html
{% extends 'base.html' %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block body %}
    <div class="col-sm-offset-3 col-sm-6">
        <br>
        <h1>Thank You For Buying Orders</h1>
        <br>
        <a href="{% url 'accounts:profile' %}">Go To Profile</a>
    </div>
{% endblock %}

orders/templates/orders/update_order.html
{% extends 'base.html' %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block body %}
    <div class="col-sm-offset-3 col-sm-6">
        <br>
        {% include 'includes/form.html' %}
    </div>
{% endblock %}