accounts/api/urls.py
from django.conf.urls import url
from .views import (
    RegisterAPIView,
    LoginAPIView,
    ProfileAPIView,
    ProfileUpdateAPIView,
    ProfileDeleteAPIView,
    ChangePasswordAPIView,
)

urlpatterns = [
    url(r'^register/', RegisterAPIView.as_view(), name='register_api'),
    url(r'^login/$', LoginAPIView.as_view(), name='login_api'),
    url(r'^change_password/$', ChangePasswordAPIView.as_view(), name='change_password_api'),
    url(r'^profile/(?P<id>\d+)/$', ProfileAPIView.as_view(), name='profile_api'),
    url(r'^profile/update/(?P<id>\d+)/$', ProfileUpdateAPIView.as_view(), name='update_api'),
    url(r'^profile/delete/(?P<id>\d+)/$', ProfileDeleteAPIView.as_view(), name='delete_api'),
]

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
    )

from .views import (
    RegisterView,
    activate_user_view,
    UserLoginView,
    UserLogoutView,
    UserChangePasswordView,
    UserProfileView,
    ProfileUpdateView,
    ProfileDeleteView,
    )

urlpatterns = [
    url(r'^activate/(?P<code>[a-zA-Z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^register/', RegisterView.as_view(), name='register'),


    url(r'^login/$', UserLoginView.as_view(), name='login'),
    url(r'^logout/$', UserLogoutView.as_view(), name='logout'),

    url(r'^change_password/$', UserChangePasswordView.as_view(), name='change_password'),

    url(r'^profile/$', UserProfileView.as_view(), name='profile'),
    url(r'^profile/update/(?P<pk>\d+)/$', ProfileUpdateView.as_view(), name='update'),
    url(r'^profile/delete/$', ProfileDeleteView.as_view(), name='delete'),


    url(r'^reset_password/$', password_reset, {
        'template_name': 'accounts/reset_password.html',
        'post_reset_redirect': 'accounts:password_reset_done',
        'email_template_name': 'accounts/reset_password_email.html',
        }, name='password_reset'),

    url(r'^reset_password/done/$', password_reset_done,
        {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'post_reset_redirect': 'accounts:password_reset_complete',
         'template_name': 'accounts/reset_password_confirm.html',
         }, name='password_reset_confirm'),

    url(r'^reset_password/complete/$', password_reset_complete,
        {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),
]

e_commerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from products.urls import ProductsListView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^contact_us/', include('contact_us.urls', namespace='contact_us')),
    url(r'^$', ProductsListView.as_view(), name='main_home'),


    url(r'^api/accounts/', include('accounts.api.urls', namespace='accounts_api')),
    url(r'^api/products/', include('products.api.urls', namespace='products_api')),
    url(r'^api/orders/', include('orders.api.urls', namespace='orders_api')),
    url(r'^api/reviews/', include('reviews.api.urls', namespace='reviews_api')),
    url(r'^api/contact_us/', include('contact_us.api.urls', namespace='contact_us_api')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url

from .views import (
    CheckoutView,
    CheckoutUpdateView,
    OrderDeleteView,
    CheckoutOrderView,
    OrdersView,
    AcceptedOrdersView,
    RejectedOrdersView,
    BuyOrdersView,
    BuyThankView,
    )

urlpatterns = [
    url(r'^order/(?P<id>\d+)/$', CheckoutView.as_view(), name='order'),
    url(r'^order/(?P<pk>\d+)/update/$', CheckoutUpdateView.as_view(), name='update'),
    url(r'^order/(?P<id>\d+)/delete/$', OrderDeleteView.as_view(), name='delete'),
    url(r'^cart/$', CheckoutOrderView.as_view(), name='checkout'),
    url(r'^pending/$', OrdersView.as_view(), name='pending'),
    url(r'^rejected/$', RejectedOrdersView.as_view(), name='rejected'),
    url(r'^accepted/$', AcceptedOrdersView.as_view(), name='accepted'),
    url(r'^thank_you/$', BuyThankView.as_view(), name='thank'),
    url(r'^buy/$', BuyOrdersView.as_view(), name='buy'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save, pre_delete
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
import os

from .utils import code_generator


User = settings.AUTH_USER_MODEL


class Gender(models.Model):
    sex = models.CharField(max_length=12)

    def __str__(self):
        return self.sex


class Account(models.Model):
    user = models.OneToOneField(User)
    username = models.CharField(max_length=255)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField(default='default.png', blank=True, null=True)
    region = models.CharField(max_length=255, blank=True, null=True)
    address1 = models.CharField(max_length=255, blank=True, null=True)
    address2 = models.CharField(max_length=255, blank=True, null=True)
    phone_number1 = models.IntegerField(blank=True, null=True)
    phone_number2 = models.IntegerField(blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    activation_key = models.CharField(max_length=120, blank=True, null=True)
    activated = models.BooleanField(default=False)
    block_review = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('accounts:update', kwargs={'pk': self.id})

    def send_activation_email(self):
        if not self.activated:
            self.activation_key = code_generator()
            self.save()
            path = reverse('accounts:activate', kwargs={'code': self.activation_key})
            subject = 'Activate Account'
            from_email = settings.DEFAULT_FROM_EMAIL
            message = 'Activate your account here: {}'.format(path)
            recipient_list = [self.user.email]
            html_message = '<p>Activate your account here: {}</p>'.format(path)
            print(html_message)
            sent_mail = send_mail(
                subject,
                message,
                from_email,
                recipient_list,
                fail_silently=False,
                html_message=html_message)
            return sent_mail


def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    if created:
        profile, is_created = Account.objects.get_or_create(
            user=instance,
            first_name=instance.first_name,
            last_name=instance.last_name,
            username=instance.username,
            email=instance.email,
        )


def pre_delete_account_img(sender, instance, *args, **kwargs):
    if instance.image:
        if instance.image == 'default.png':
            pass
        else:
            if os.path.isfile(instance.image.path):
                os.remove(instance.image.path)


pre_delete.connect(pre_delete_account_img, sender=Account)
post_save.connect(post_save_user_receiver, sender=User)

accounts/api/views.py
from rest_framework.generics import (
    CreateAPIView,
    RetrieveAPIView,
    RetrieveUpdateAPIView,
    UpdateAPIView,
    DestroyAPIView,
)

from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated, AllowAny

from django.contrib.auth import get_user_model, update_session_auth_hash

from .serializers import (
    RegisterSerializer,
    LoginSerializer,
    ProfileSerializer,
    UpdateSerializer,
    ChangePasswordSerializer,
)
from accounts.models import Account
from .permissions import IsOwnerOrReadOnly

User = get_user_model()


class RegisterAPIView(CreateAPIView):
    serializer_class = RegisterSerializer
    queryset = ''
    permission_classes = [AllowAny, ]


class LoginAPIView(APIView):
    serializer_class = LoginSerializer
    permission_classes = [AllowAny, ]

    def post(self, request):
        serializer = LoginSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            new_data = serializer.data
            return Response(new_data, status=HTTP_200_OK)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)


class ProfileAPIView(RetrieveAPIView):
    serializer_class = ProfileSerializer
    lookup_url_kwarg = 'id'
    lookup_field = 'id'
    permission_classes = [IsOwnerOrReadOnly, IsAuthenticated]

    def get_queryset(self, *args, **kwargs):
        queryset = Account.objects.filter(user=self.request.user, id=self.kwargs['id'], activated=True)
        return queryset


class ProfileUpdateAPIView(RetrieveUpdateAPIView):
    serializer_class = UpdateSerializer
    lookup_field = 'user'
    lookup_url_kwarg = 'id'
    permission_classes = [IsOwnerOrReadOnly, IsAuthenticated]

    def get_queryset(self, *args, **kwargs):
        queryset = Account.objects.filter(user=self.request.user, id=self.kwargs['id'], activated=True)
        return queryset


class ProfileDeleteAPIView(DestroyAPIView):
    serializer_class = ProfileSerializer
    lookup_field = 'id'
    permission_classes = [IsOwnerOrReadOnly, IsAuthenticated]

    def get_queryset(self, *args, **kwargs):
        queryset = User.objects.filter(username=self.request.user, id=self.kwargs['id'], is_active=True)
        return queryset


class ChangePasswordAPIView(UpdateAPIView):
    serializer_class = ChangePasswordSerializer
    model = User
    permission_classes = [IsOwnerOrReadOnly, IsAuthenticated]

    def get_object(self):
        return self.request.user

    def update(self, request, *args, **kwargs):
        # self.object = self.get_object()
        user = self.get_object()
        serializer = self.get_serializer(data=request.data)
        # serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            if not user.check_password(serializer.data.get("old_password")):
                return Response({"old_password": ["Wrong password"]}, status=HTTP_400_BAD_REQUEST)
            user.set_password(serializer.data.get("new_password"))
            user.save()
            update_session_auth_hash(request, user)
            return Response({'message': ['Success!']}, status=HTTP_200_OK)

        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.views.generic import CreateView, DetailView, UpdateView, View
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.conf import settings
from django.urls import reverse_lazy

from .forms import RegisterForm, LoginForm, UpdateProfileForm
from .models import Account


User = get_user_model()


def activate_user_view(request, code=None):
    if code:
        qs = Account.objects.filter(activation_key=code)
        if qs.exists() and qs.count() == 1:
            account = qs.first()
            if not account.activated:
                user = account.user
                user.is_active = True
                user.save()
                account.activated = True
                account.activation_key = None
                account.save()
                return redirect("accounts:login")
    return redirect("accounts:login")


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = settings.LOGIN_REDIRECT_URL

    def get_context_data(self, **kwargs):
        context = super(RegisterView, self).get_context_data(**kwargs)
        context['title'] = 'Register'
        return context


class UserLoginView(View):
    form_class = LoginForm
    template_name = 'accounts/login.html'

    def get(self, request):
        form = self.form_class(None)
        context = {
                'form': form,
                'title': 'Login'
            }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('accounts:profile')
        context = {
            'form': form,
            'title': 'Login'
        }
        return render(request, self.template_name, context)


class UserLogoutView(View):
    template_name = 'accounts/login.html'

    def get(self, request):
        logout(request)
        return redirect('accounts:login')


class UserChangePasswordView(View):
    form_class = PasswordChangeForm
    template_name = 'accounts/change_password.html'

    def get(self, request):
        form = self.form_class(None)
        context = {
            'form': form,
            'title': 'Change Password'
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:profile')
        context = {
            'form': form,
            'title': 'Change Password'
        }
        return render(request, self.template_name, context)


class UserProfileView(DetailView):
    template_name = 'accounts/profile.html'

    def get_object(self):
        username = self.request.user
        if username is None:
            raise Http404
        return get_object_or_404(User, username__iexact=username, is_active=True)

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['title'] = 'Profile'
        return context


class ProfileUpdateView(UpdateView):
    form_class = UpdateProfileForm
    model = Account
    template_name = 'accounts/update_profile.html'
    success_url = reverse_lazy('accounts:profile')

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Update Profile'
        return context


class ProfileDeleteView(View):
    template_name = 'accounts/profile.html'

    def post(self, request):
        username = self.request.user
        if username is None:
            raise Http404
        else:
            qs = User.objects.filter(username=self.request.user)
            if qs.exists() and qs.count() == 1:
                account = qs.first()
                account.delete()
                return redirect('accounts:login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block body %}
    <div class="col-sm-offset-3 col-sm-6">
        <br>
        {% include 'includes/form.html' %}
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block body %}
    <div class="col-sm-offset-3 col-sm-6">
        <br>
        {% include 'includes/form.html' %}
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load static %}

{% load mathfilters %}

{% block title %}
    {{ user }}'s {{ title }} | {{ block.super }}
{% endblock %}

{% block body %}

{#    <!-- Button trigger modal -->#}
{#    <button class="btn btn-danger" href="" data-toggle="modal" data-target="#delete_account">#}
{#      Delete My Account#}
{#    </button>#}

{#    <!-- delete account modal -->#}
{#    <!-- Modal -->#}
{#    <div class="modal fade" id="delete_account" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">#}
{#      <div class="modal-dialog" role="document">#}
{#        <div class="modal-content" style="border-radius: 6px;">#}
{#          <div class="modal-header">#}
{#            <h5 class="modal-title" id="exampleModalLabel">Delete Account</h5>#}
{#            <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: -21px;">#}
{#              <span aria-hidden="true">&times;</span>#}
{#            </button>#}
{#          </div>#}
{#          <div class="modal-body">#}
{#            Are you sure you want to delete your account?#}
{#          </div>#}
{#          <div class="modal-footer">#}
{#            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>#}
{#            <form method="post" action="{% url 'accounts:delete' %}" style="display: inline-block;">#}
{#                {% csrf_token %}#}
{#                <a href="{% url 'accounts:delete' %}">#}
{#                    <button class="btn btn-danger">#}
{#                        Confirm Delete#}
{#                    </button>#}
{#                </a>#}
{#            </form>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}

{#    <br>#}
{#    <br>#}
{#    <a href="{% url 'accounts:delete' %}" class="btn btn-danger">delete</a>#}
{#    <p class="lead">Hello : {{ user.username }}</p>#}
{#    <p class="lead">First Name : {{ user.first_name }}</p>#}
{#    <p class="lead">Last Name : {{ user.last_name }}</p>#}
{#    <p class="lead">Last login : {{ user.last_login }}</p>#}
{#    <p class="lead">Joined in : {{ user.date_joined }}</p>#}
{#    {% if user.account.phone_number1 %}#}
{#        <p class="lead">Phone Number 1 : {{ user.account.phone_number1 }}</p>#}
{#    {% endif %}#}
{#    {% if user.account.phone_number2 %}#}
{#        <p class="lead">Phone Number 2 : {{ user.account.phone_number2 }}</p>#}
{#    {% endif %}#}
{#    {% if user.account.gender %}#}
{#        <p class="lead">Gender : {{ user.account.gender }}</p>#}
{#    {% endif %}#}
{#    {% if user.account.country %}#}
{#        <p class="lead">Country : {{ user.account.country }}</p>#}
{#    {% endif %}#}
{#    {% if user.account.region %}#}
{#        <p class="lead">Region : {{ user.account.region }}</p>#}
{#    {% endif %}#}
{#    {% if user.account.address1 %}#}
{#        <p class="lead">Address1 : {{ user.account.address1 }}</p>#}
{#    {% endif %}#}
{#    {% if user.account.address2 %}#}
{#        <p class="lead">Address2 : {{ user.account.address2 }}</p>#}
{#    {% endif %}#}
{#    {% if user.account.comments %}#}
{#        <p class="lead">Comments : {{ user.account.comments }}</p>#}
{#    {% endif %}#}
{#    {% if user.account.image != 'defauli.png' %}#}
{#        <p class="lead">Image : <img src="{{ user.account.image.url }}" alt="{{ user.username }}" class="img-responsive" style="max-width: 25%; max-height: 25%;"></p>#}
{#    {% elif user.account.image == 'defauli.png' %}#}
{#        <p class="lead">Image : <img src="{% static 'default.png' %}" alt="{{ user.username }}" class="img-responsive" style="max-width: 25%; max-height: 25%;"></p>#}
{#    {% endif %}#}


	<section>
		<div class="container-fluid">
			<div class="row">
            <div class="card">

                <div class="card-body">
                    <h3 class="text-center" style="margin-top: 0;">Hello {{ user.username }}</h3>
                    <br>
                    <br>
                    <br>
                    <br>
                    {% if user.account.image != 'defauli.png' %}
                        <p class="lead"><img src="{{ user.account.image.url }}" alt="{{ user.username }}" class="img-responsive" style="max-width: 20%; max-height: 20%; display: block; margin: -65px auto 65px; border-radius: 6px;"></p>
                    {% elif user.account.image == 'defauli.png' %}
                        <p class="lead"><img src="{% static 'default.png' %}" alt="{{ user.username }}" class="img-responsive" style="max-width: 20%; max-height: 20%; display: block; margin: -65px auto 65px; border-radius: 6px;"></p>
                    {% endif %}

                    <table class="table table-responsive">
                        <thead>
                          <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Phone Number 1</th>
                            <th>Phone Number 2</th>
                            <th>Gender</th>
                            <th>Address1</th>
                            <th>Address2</th>
                            <th>Comments</th>
                            <th>Region</th>
                            <th>Country</th>
                            <th>Joined In</th>
                            <th>Last login</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.account.phone_number1 }}</td>
                            <td>{{ user.account.phone_number2 }}</td>
                            <td>{{ user.account.gender }}</td>
                            <td>{{ user.account.address1 }}</td>
                            <td>{{ user.account.address2 }}</td>
                            <td>{{ user.account.comments }}</td>
                            <td>{{ user.account.region }}</td>
                            <td>{{ user.account.country }}</td>
                            <td>{{ user.date_joined }}</td>
                            <td>{{ user.last_login | timesince }}</td>
                          </tr>
                        </tbody>
                      </table>
{#                      <hr>#}
{##}
{#                      <table class="table table-striped">#}
{#                        <thead>#}
{#                          <tr>#}
{#                            <th>Product Name</th>#}
{#                            <th>Status</th>#}
{#                            <th>Quantity</th>#}
{#                            <th>Price</th>#}
{#                            <th>Discount</th>#}
{#                            <th>Total</th>#}
{#                            <th>Order Date</th>#}
{#                          </tr>#}
{#                        </thead>#}
{#                        <tbody>#}
{#                        {% for order in orders %}#}
{#                          <tr>#}
{#                            <td><a href="{% url 'orders:update' pk=order.id %}">{{ order.name }}</a></td>#}
{#                            <td>{{ order.status }}</td>#}
{#                            <td>{{ order.quantity }}</td>#}
{#                            <td>{{ order.price }}</td>#}
{#                            <td>{{ order.discount }}</td>#}
{#                            <td>{{ order.price |mul:order.discount |div:100 |sub:order.price |mul:-1 |mul:order.quantity }}</td>#}
{#                            <td>{{ (order.price - order.discount) * order.quantity }}</td>#}
{#                            <td>{{ order.added | timesince }}</td>#}
{#                          </tr>#}
{#                        {% endfor %}#}
{#                        </tbody>#}
{#                      </table>#}
                      <br>
                      <br>
                      <br>
                      <br>
                      <br>
                      <br>
                </div>
            </div>

			</div>
		</div>
	</section>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block body %}
    <div class="col-sm-offset-3 col-sm-6">
        <br>
        {% include 'includes/form.html' %}
    </div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block title %}
{#    {{ title }} | {{ block.super }}#}
    Reset Password | {{ block.super }}
{% endblock %}

{% block body %}
    <div class="col-sm-offset-3 col-sm-6">
        <h1>Reset Password</h1>
{#        <h1>{{ title }}</h1>#}
        <p>
            Forgotten your password? Enter your email address below,
            and we'll email instructions for setting a new one.
        </p>
        <br>
        <br>
{#        {% include 'includes/form.html' %}#}
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Reset Password" class="btn btn-primary">
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block body %}
    <div class="col-sm-offset-3 col-sm-6">
        <br>
        <h1>{{ title }}!</h1>
{#        <h1>Password reset complete!</h1>#}
        <p>
            Your password has been set.
            You may go ahead and log in now.
        </p>
        <br>
        <a href="{% url 'accounts:login' %}">Login</a>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block title %}
    {{ title }} | {{ block.super }}
{#    Reset Password | {{ block.super }}#}
{% endblock %}

{% block body %}
    <div class="col-sm-offset-3 col-sm-6">
        <br>
        <h1>{{ title }}!</h1>
{#        <h1>Reset Password!</h1>#}
        {% if validlink %}
            <p>
                Please enter your new password twice so we can verify you typed it in correctly.
            </p>
            <br>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Reset Password" class="btn btn-primary">
            </form>
        {% else %}
            <p>
                The password reset link was invalid,
                possibly because it has already been used.
                Please request a new password reset.
            </p>
        {% endif %}
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block body %}
    <div class="col-sm-offset-3 col-sm-6">
        <h1>Password reset sent!</h1>
        <p>
            We've emailed you instructions for setting your password,
            if an account exists with the email you entered.
            You should receive them shortly.

            If you don't receive an email,
            please make sure you've entered the address you registered with,
            and check your spam folder.
        </p>
        <br>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}
    You're receiving this email because you requested a password reset
    for your user account at {{ site_name }}.
{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
    {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/update_profile.html
{% extends 'base.html' %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block body %}
    <div class="col-sm-offset-3 col-sm-6">
        <br>
        {% include 'includes/form.html' %}
    </div>
{% endblock %}