accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
    )

from .views import (
    RegisterView,
    activate_user_view,
    UserLoginView,
    UserLogoutView,
    UserChangePasswordView,
    UserProfileView,
    ProfileUpdateView,
    ProfileDeleteView,
    )

urlpatterns = [
    url(r'^activate/(?P<code>[a-zA-Z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^register/', RegisterView.as_view(), name='register'),


    url(r'^login/$', UserLoginView.as_view(), name='login'),
    url(r'^logout/$', UserLogoutView.as_view(), name='logout'),

    url(r'^change_password/$', UserChangePasswordView.as_view(), name='change_password'),

    url(r'^profile/$', UserProfileView.as_view(), name='profile'),
    url(r'^profile/update/(?P<pk>\d+)/$', ProfileUpdateView.as_view(), name='update'),
    url(r'^profile/delete/$', ProfileDeleteView.as_view(), name='delete'),


    url(r'^reset_password/$', password_reset, {
        'template_name': 'accounts/reset_password.html',
        'post_reset_redirect': 'accounts:password_reset_done',
        'email_template_name': 'accounts/reset_password_email.html',
        }, name='password_reset'),

    url(r'^reset_password/done/$', password_reset_done,
        {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'post_reset_redirect': 'accounts:password_reset_complete',
         'template_name': 'accounts/reset_password_confirm.html',
         }, name='password_reset_confirm'),

    url(r'^reset_password/complete/$', password_reset_complete,
        {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),
]

e_commerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from products.urls import ProductsListView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^contact_us/', include('contact_us.urls', namespace='contact_us')),
    url(r'^$', ProductsListView.as_view(), name='main_home'),


    url(r'^api/accounts/', include('accounts.api.urls', namespace='accounts_api')),
    url(r'^api/products/', include('products.api.urls', namespace='products_api')),
    url(r'^api/orders/', include('orders.api.urls', namespace='orders_api')),
    url(r'^api/reviews/', include('reviews.api.urls', namespace='reviews_api')),
    url(r'^api/contact_us/', include('contact_us.api.urls', namespace='contact_us_api')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url

from .views import (
    CheckoutView,
    CheckoutUpdateView,
    OrderDeleteView,
    CheckoutOrderView,
    OrdersView,
    AcceptedOrdersView,
    RejectedOrdersView,
    BuyOrdersView,
    BuyThankView,
    )

urlpatterns = [
    url(r'^order/(?P<id>\d+)/$', CheckoutView.as_view(), name='order'),
    url(r'^order/(?P<pk>\d+)/update/$', CheckoutUpdateView.as_view(), name='update'),
    url(r'^order/(?P<id>\d+)/delete/$', OrderDeleteView.as_view(), name='delete'),
    url(r'^cart/$', CheckoutOrderView.as_view(), name='checkout'),
    url(r'^pending/$', OrdersView.as_view(), name='pending'),
    url(r'^rejected/$', RejectedOrdersView.as_view(), name='rejected'),
    url(r'^accepted/$', AcceptedOrdersView.as_view(), name='accepted'),
    url(r'^thank_you/$', BuyThankView.as_view(), name='thank'),
    url(r'^buy/$', BuyOrdersView.as_view(), name='buy'),
]

products/urls.py
from django.conf.urls import url

from .views import (
    ProductsListView,
    ProductDetailView,
    AllProductsListView,
    CategoryListView,
    )

urlpatterns = [
    url(r'^category/(?P<category>[a-zA-Z0-9].*)/$', CategoryListView.as_view(), name='category'),
    url(r'^all/$', AllProductsListView.as_view(), name='all'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail'),
    url(r'^$', ProductsListView.as_view(), name='list'),
]

templates/includes/css.html
{% load static %}

<link rel="shortcut icon" href="{%  static 'i.ico' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">






<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">



<link rel="stylesheet" href="{% static 'css/style.css' %}">











<link rel="stylesheet" href="{% static 'css/base.css' %}">

templates/includes/delete_account_modal.html
<!-- Modal -->
<div class="modal fade" id="delete_account" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="border-radius: 6px;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Account</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: -21px;">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your account permanently?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form method="post" action="{% url 'accounts:delete' %}" style="display: inline-block;">
            {% csrf_token %}
{#                <a href="{% url 'accounts:delete' %}">#}
                <button class="btn btn-danger">
                    Confirm Delete
                </button>
{#                </a>#}
        </form>
      </div>
    </div>
  </div>
</div>

templates/includes/form.html
{#{% if form.errors.non_field_errors %}#}
{#    {{ form.errors.non_field_errors }}#}
{#{% endif %}#}

{#{% if form.errors %}#}
{#    {{ form.errors }}#}
{#{% endif %}#}

{% load crispy_forms_tags %}

<form method="POST" enctype="multipart/form-data" action="" class="form-group">
    {% csrf_token %}
{#    {% crispy form %}#}
{#    {% form |crispy %}#}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">{{ title }}</button>
</form>

{#{% if form.instance %}#}
{#    <h1>{{ form.instance }}</h1>#}
{#{% endif %}#}

templates/includes/js.html
{% load static %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/active_url.js' %}"></script>
<script src="{% static 'js/update_review_form.js' %}"></script>
<script src="{% static 'js/update_order_form.js' %}"></script>







<script src="{% static 'js/main.js' %}"></script>

templates/includes/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
{#            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>#}
{#                {% if 'html_safe' in message.tags %}#}
{#                    {{ message | safe }}#}
{#                {% else %}#}
{#                    {{ message }}#}
{#                {% endif %}#}
{#            </li>#}
        {% endfor %}
    </ul>
{% endif %}

templates/includes/nav_bar.html
{% load static %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'main_home' %}">
          OSAMA MOHAMED
{#          <img alt="Brand" src="{% static 'brand.png' %}">#}
      </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
{#        <li class="dropdown">#}
{#          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>#}
{#          <ul class="dropdown-menu">#}
{#            <li><a href="#">Separated link</a></li>#}
{#            <li role="separator" class="divider"></li>#}
{#          </ul>#}
{#        </li>#}
      </ul>
      <form method="post" action="{% url 'products:list' %}" class="navbar-form navbar-left">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" name="search" value="{{ request.POST.search }}" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'products:list' %}">Home</a></li>
        <li><a href="{% url 'products:all' %}">All Products</a></li>
        {% if request.user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Orders <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'orders:checkout' %}">Cart</a></li>
            <li><a href="{% url 'orders:pending' %}">Pending Orders</a></li>
            <li><a href="{% url 'orders:accepted' %}">Accepted Orders</a></li>
            <li><a href="{% url 'orders:rejected' %}">Rejected Orders</a></li>
{#            <li role="separator" class="divider"></li>#}
          </ul>
        </li>
        {% endif %}
        <li class="dropdown">
          {% if request.user.is_authenticated %}
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
          {% else %}
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Register/Login <span class="caret"></span></a>
          {% endif %}
          <ul class="dropdown-menu">
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                <li><a href="{% url 'accounts:update' pk=user.account.id%}">Update Profile</a></li>
                <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>

                <li>
                    <a href="" data-toggle="modal" data-target="#delete_account">
                      Delete My Account
                    </a>
                </li>

                <li role="separator" class="divider"></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'accounts:register' %}">Register</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'accounts:password_reset' %}">Reset Password</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

{% include 'includes/delete_account_modal.html' %}