accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
    )

from .views import (
    RegisterView,
    activate_user_view,
    UserLoginView,
    UserLogoutView,
    UserChangePasswordView,
    UserProfileView,
    ProfileUpdateView,
    ProfileDeleteView,
    )

urlpatterns = [
    url(r'^activate/(?P<code>[a-zA-Z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^register/', RegisterView.as_view(), name='register'),


    url(r'^login/$', UserLoginView.as_view(), name='login'),
    url(r'^logout/$', UserLogoutView.as_view(), name='logout'),

    url(r'^change_password/$', UserChangePasswordView.as_view(), name='change_password'),

    url(r'^profile/$', UserProfileView.as_view(), name='profile'),
    url(r'^profile/update/(?P<pk>\d+)/$', ProfileUpdateView.as_view(), name='update'),
    url(r'^profile/delete/$', ProfileDeleteView.as_view(), name='delete'),


    url(r'^reset_password/$', password_reset, {
        'template_name': 'accounts/reset_password.html',
        'post_reset_redirect': 'accounts:password_reset_done',
        'email_template_name': 'accounts/reset_password_email.html',
        }, name='password_reset'),

    url(r'^reset_password/done/$', password_reset_done,
        {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'post_reset_redirect': 'accounts:password_reset_complete',
         'template_name': 'accounts/reset_password_confirm.html',
         }, name='password_reset_confirm'),

    url(r'^reset_password/complete/$', password_reset_complete,
        {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),
]

e_commerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from products.urls import ProductsListView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^contact_us/', include('contact_us.urls', namespace='contact_us')),
    url(r'^$', ProductsListView.as_view(), name='main_home'),


    url(r'^api/accounts/', include('accounts.api.urls', namespace='accounts_api')),
    url(r'^api/products/', include('products.api.urls', namespace='products_api')),
    url(r'^api/orders/', include('orders.api.urls', namespace='orders_api')),
    url(r'^api/reviews/', include('reviews.api.urls', namespace='reviews_api')),
    url(r'^api/contact_us/', include('contact_us.api.urls', namespace='contact_us_api')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url

from .views import (
    CheckoutView,
    CheckoutUpdateView,
    OrderDeleteView,
    CheckoutOrderView,
    OrdersView,
    AcceptedOrdersView,
    RejectedOrdersView,
    BuyOrdersView,
    BuyThankView,
    )

urlpatterns = [
    url(r'^order/(?P<id>\d+)/$', CheckoutView.as_view(), name='order'),
    url(r'^order/(?P<pk>\d+)/update/$', CheckoutUpdateView.as_view(), name='update'),
    url(r'^order/(?P<id>\d+)/delete/$', OrderDeleteView.as_view(), name='delete'),
    url(r'^cart/$', CheckoutOrderView.as_view(), name='checkout'),
    url(r'^pending/$', OrdersView.as_view(), name='pending'),
    url(r'^rejected/$', RejectedOrdersView.as_view(), name='rejected'),
    url(r'^accepted/$', AcceptedOrdersView.as_view(), name='accepted'),
    url(r'^thank_you/$', BuyThankView.as_view(), name='thank'),
    url(r'^buy/$', BuyOrdersView.as_view(), name='buy'),
]

products/api/urls.py
from django.conf.urls import url
from .views import (
    AllProductsAPIView,
    ProductsAPIView,
    ProductDetailAPIView,
    CategoryAPIView,
)

urlpatterns = [
    url(r'^category/(?P<category>[a-zA-Z0-9].*)/$', CategoryAPIView.as_view(), name='category_api'),
    url(r'^all/$', AllProductsAPIView.as_view(), name='all_api'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailAPIView.as_view(), name='detail_api'),
    url(r'^$', ProductsAPIView.as_view(), name='list_api'),
]

products/urls.py
from django.conf.urls import url

from .views import (
    ProductsListView,
    ProductDetailView,
    AllProductsListView,
    CategoryListView,
    )

urlpatterns = [
    url(r'^category/(?P<category>[a-zA-Z0-9].*)/$', CategoryListView.as_view(), name='category'),
    url(r'^all/$', AllProductsListView.as_view(), name='all'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail'),
    url(r'^$', ProductsListView.as_view(), name='list'),
]

reviews/urls.py
from django.conf.urls import url

from .views import (
    AddReviewView,
    UpdateReviewView,
    DeleteReviewView,
    )

urlpatterns = [
    url(r'^add_review/(?P<id>\d+)/$', AddReviewView.as_view(), name='add'),
    url(r'^update_review/(?P<id>\d+)/$', UpdateReviewView.as_view(), name='update'),
    url(r'^delete_review/(?P<id>\d+)/$', DeleteReviewView.as_view(), name='delete'),
]

products/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save, pre_delete
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
import os

from .utils import create_slug


User = get_user_model()


class Category(models.Model):
    category = models.CharField(max_length=255, unique=True)
    number_of_products = models.IntegerField(default=0, blank=True, null=True)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.category

    def get_absolute_categories_url(self):
        return reverse('products:category', kwargs={'category': self.category})

    class Meta:
        verbose_name_plural = 'Categories'


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True, null=True)
    name = models.CharField(max_length=255)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    discount = models.FloatField(default=0, blank=True, null=True)
    number_of_sales = models.PositiveIntegerField(default=0, blank=True, null=True)
    number_of_views = models.PositiveIntegerField(default=0, blank=True, null=True)
    avg_rate = models.FloatField(default=0, blank=True, null=True)
    description = models.TextField()
    image = models.ImageField()
    slider = models.BooleanField(default=False)
    publish = models.BooleanField(default=True)
    block_review = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug': self.slug})


def pre_save_post_reciver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    if created:
        qs = Product.objects.filter(slug=instance)
        if qs.exists() and qs.count() == 1:
            product = qs.first()
            category = Category.objects.get(category=product.category)
            category.number_of_products += 1
            category.save()


def pre_delete_product_img(sender, instance, *args, **kwargs):
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


pre_save.connect(pre_save_post_reciver, sender=Product)
post_save.connect(post_save_user_receiver, sender=Product)
pre_delete.connect(pre_delete_product_img, sender=Product)

products/api/views.py
from rest_framework.generics import (
    RetrieveAPIView,
    ListAPIView,
)

from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.permissions import AllowAny

from django.db.models import Q

from .serializers import (
    ProductsSerializer,
    ProductDetailSerializer,
)
from products.models import Product
from .pagination import ProductPageNumberPagination


class AllProductsAPIView(ListAPIView):
    serializer_class = ProductsSerializer
    pagination_class = ProductPageNumberPagination
    permission_classes = [AllowAny, ]

    def get_queryset(self, *args, **kwargs):
        queryset = Product.objects.filter(publish=True).order_by('-id')
        return queryset


class ProductsAPIView(ListAPIView):
    serializer_class = ProductsSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['name', 'description']
    permission_classes = [AllowAny, ]

    def get_queryset(self, *args, **kwargs):
        queryset = Product.objects.filter(publish=True).order_by('-id')
        query = self.request.GET.get('search')
        if query:
            queryset = Product.objects.filter(
                                              Q(name__icontains=query) |
                                              Q(description__icontains=query)
                                              , publish=True).distinct()
        return queryset


class ProductDetailAPIView(RetrieveAPIView):
    serializer_class = ProductDetailSerializer
    lookup_field = 'slug'
    permission_classes = [AllowAny, ]

    def get_queryset(self, *args, **kwargs):
        queryset = Product.objects.filter(slug__iexact=self.kwargs['slug'], publish=True)
        return queryset


class CategoryAPIView(ListAPIView):
    serializer_class = ProductsSerializer
    pagination_class = ProductPageNumberPagination
    permission_classes = [AllowAny, ]

    def get_queryset(self, *args, **kwargs):
        queryset = Product.objects.filter(publish=True, category__category=self.kwargs['category']).order_by('-id')
        return queryset

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q


from .models import Product, Category
from reviews.models import Review


class AllProductsListView(ListView):
    queryset = Product.objects.all().order_by('-id')
    template_name = 'products/all_products.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(AllProductsListView, self).get_context_data(**kwargs)

        qs = Product.objects.all().order_by('-id')
        paginator = Paginator(qs, self.paginate_by)
        page_request = 'page'
        page = self.request.GET.get(page_request)
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            queryset = paginator.page(1)
        except EmptyPage:
            queryset = paginator.page(paginator.num_pages)
        context['objects'] = queryset
        context['page_request'] = page_request

        context['title'] = 'All Products'
        return context


class ProductsListView(ListView):
    queryset = ''
    template_name = 'products/product_list.html'

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context['title'] = 'Home'
        context['latest_products'] = Product.objects.all().order_by('-id')[:6]  # [start(offset):stop(limit):step]
        context['recommended'] = Product.objects.all().order_by('number_of_sales')[:3]
        context['recommended_2'] = Product.objects.all().order_by('number_of_sales')[3:6]
        context['categories'] = Category.objects.all().order_by('category')
        context['active_slider'] = Product.objects.filter(slider=True)[:1]
        context['non_active_slider_1'] = Product.objects.filter(slider=True)[1:2]
        context['non_active_slider_2'] = Product.objects.filter(slider=True)[2:3]
        return context

    def post(self, request):
        minimum = self.request.POST.get('minimum')
        maximum = self.request.POST.get('maximum')
        search = self.request.POST.get('search')
        if search == '':
            return redirect('products:list')
        if search:
            queryset = Product.objects.filter(
                Q(name__icontains=search) |
                Q(description__icontains=search) |
                Q(category__category__icontains=search)
            ).distinct().order_by('-id')
            context = {
                'products': queryset,
                'categories': Category.objects.all().order_by('category'),
                'title': 'Search',
            }
            return render(request, 'products/categories.html', context)
        if not minimum == '' and not maximum == '':
            queryset = Product.objects.filter(price__range=(minimum, maximum)).order_by('-id')
            context = {
                'products': queryset,
                'categories': Category.objects.all().order_by('category'),
                'title': 'Price Range',
            }
            return render(request, 'products/categories.html', context)
        else:
            return redirect('products:list')


class ProductDetailView(DetailView):
    template_name = 'products/product_detail.html'

    def get_object(self):
        slug = self.kwargs['slug']
        product = Product.objects.filter(slug=slug).first()
        product.number_of_views += 1
        product.save()
        return get_object_or_404(Product, slug=slug, publish=True)

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['recommended'] = Product.objects.all().order_by('number_of_sales')[:3]
        context['categories'] = Category.objects.all().order_by('category')
        context['reviews'] = Review.objects.filter(product__slug=self.kwargs['slug']).order_by('-id')
        context['review'] = Review.objects.filter(product__slug=self.kwargs['slug']).order_by('-id')[:1].first()
        try:
            context['review_form'] = Review.objects.filter(product__slug=self.kwargs['slug'], user=self.request.user).order_by('-id')[:1].first()
        except:
            pass
        return context


class CategoryListView(ListView):
    queryset = ''
    template_name = 'products/categories.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['title'] = 'Category'
        context['categories'] = Category.objects.all().order_by('category')
        context['products'] = Product.objects.filter(category__category=self.kwargs['category']).order_by('-id')
        context['current_category'] = self.kwargs['category']
        return context

products/templates/products/add_review_form.html
<p><b>Write Your Review</b></p>
<form action="{% url 'reviews:add' id=product.id %}" method="POST" class="form-group">
    {% csrf_token %}
    <textarea name="review" cols="102" rows="6"></textarea>
    <br>
    <b>Rate: </b> &emsp;
    <select name="rate" style="width: 80px;" class="btn btn-default dropdown-toggle">
        <option value="5">5</option>
        <option value="4">4</option>
        <option value="3">3</option>
        <option value="2">2</option>
        <option value="1">1</option>
    </select>
    <br>
    <br>
    <button type="submit" class="btn btn-primary pull-left">
        Add Review
    </button>
</form>

products/templates/products/all_products.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ title }} | {{ block.super }}
{% endblock %}

{% block body %}

	<section>
		<div class="container-fluid">
			<div class="row">

				<div class="col-sm-12 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">All Products</h2>


                        {% for product in object_list %}
						<div class="col-sm-3">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
                                        <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" class="image-thumbnail"></a>
										<h2>&#36;{{ product.price }}</h2>
                                        {% if product.discount %}
{#                                            <h3 style="color: red;">{{ ((100 * product.discount) / product.price) | int}} &#37; OFF</h3>#}
                                            <h3 style="color: red;">{{  product.discount }}  &#37; OFF</h3>
                                        {% else %}
                                            <h3 style="color: red;">0 &#37; OFF</h3>
                                        {% endif %}
										<p style="max-width: 252px; overflow: hidden;">{{ product.name | truncatechars:30 }}</p>
                                        <p><b>AVG Rate:</b>&emsp;
                                        {% if product.avg_rate %}
                                            {{ product.avg_rate | floatformat:-2 }}
                                            &#47; {{ 5 }}
                                        {% elif product.avg_rate == 0 %}
                                        {{ 'Not Rated Yet' }}
                                        {% endif %}
                                        </p>
                                        {% if product.quantity == 1 or product.quantity > 1  %}
										    {% if request.user.is_authenticated %}
                                                <form action="{% url 'orders:order' id=product.id %}" method="POST">
                                                    {% csrf_token %}
                                                    <input type="hidden" value="{{ product.id }}" name="id">
                                                    <button class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
    {#										    <a href="{% url 'orders:order' id=product.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>#}
                                                </form>
                                            {% else %}
                                                <a href="{% url 'accounts:login' %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Log In to buy</a>
                                            {% endif %}
                                        {% elif product.quantity == 0 %}
                                            <a href="" class="btn btn-danger" style="margin-bottom: 24px; border-radius: 0;" disabled=""><i class="fa fa-shopping-cart" style="margin-right: 5px;"></i>Out Of Stock</a>
                                        {% endif %}
									</div>
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
{#										<li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>#}
									</ul>
								</div>
							</div>
						</div>
                        {% endfor %}


						<ul class="pagination">

                            <div class="pagination"> <!-- page_request == the name of page that i want like:page -->
                                <span class="step-links"> <!-- objects == the number of pages -->
                                    {% if objects.has_previous %}
                                        <a href="?{{ page_request }}={{ objects.previous_page_number }}
                                            {% if request.GET.search_post %}
                                                &search_post={{ request.GET.search_post }}
                                            {% endif %}">previous
                                        </a>
                                    {% endif %}

                                    <span class="current">
                                        Page {{ objects.number }} of {{ objects.paginator.num_pages }}.
                                    </span>

                                    {% if objects.has_next %}
                                        <a href="?{{ page_request }}={{ objects.next_page_number }}
                                            {% if request.GET.search_post %}
                                                &search_post={{ request.GET.search_post }}
                                            {% endif %}">next
                                        </a>
                                    {% endif %}
                                </span>
                            </div>

                            {% if is_paginated %}
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li>
                                            <span>
                                                <a href="?page={{ page_obj.previous_page_number }}">
                                                    Previous
                                                </a>
                                            </span>
                                        </li>
                                    {% endif %}
                                    <li class="">
                                        <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                                    </li>
                                    {% if page_obj.has_next %}
                                        <li>
                                            <span>
                                                <a href="?page={{ page_obj.next_page_number }}">
                                                    Next
                                                </a>
                                            </span>
                                        </li>
                                    {% endif %}
                                </ul>
                            {% endif %}
						</ul>
					</div><!--features_items-->
				</div>
			</div>
		</div>
	</section>

{% endblock %}

products/templates/products/categories.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ title }} {{ current_category.upper }} | {{ block.super }}
{% endblock %}

{% block body %}

	<section>
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Categories</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->

                            {% for category in categories %}
                                <div class="panel panel-default">
                                    <div class="panel-heading">
    									<h4 class="panel-title"><a href="{{ category.get_absolute_categories_url }}">{{ category }} &emsp; ({{ category.number_of_products }})</a></h4>
                                    </div>
                                </div>
							{% endfor %}

						</div><!--/category-products-->

					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">{{ title }} {{ current_category }} Products</h2>
						<h2 class="title text-center">
                            {% if products.count == 1 %}
                                Found {{ products | length }} product
                            {% elif products.count == 0 %}
                                no products found!
                            {% else %}
                                Found {{ products | length }} products
                            {% endif %}
                        </h2>

                        {% for product in products %}
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
                                        <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" class="image-thumbnail"></a>
										<h2>&#36;{{ product.price }}</h2>
                                        {% if product.discount %}
{#                                            <h3 style="color: red;">{{ ((100 * product.discount) / product.price) | int}} &#37; OFF</h3>#}
                                            <h3 style="color: red;">{{  product.discount }}  &#37; OFF</h3>
                                        {% else %}
                                            <h3 style="color: red;">0 &#37; OFF</h3>
                                        {% endif %}
										<p style="max-width: 252px; overflow: hidden;">{{ product.name | truncatechars:30 }}</p>
                                        <p><b>AVG Rate:</b>&emsp;
                                        {% if product.avg_rate %}
                                            {{ product.avg_rate | floatformat:-2 }}
                                            &#47; {{ 5 }}
                                        {% elif product.avg_rate == 0 %}
                                        {{ 'Not Rated Yet' }}
                                        {% endif %}
                                        </p>
                                        {% if product.quantity == 1 or product.quantity > 1  %}
										    {% if request.user.is_authenticated %}
                                                <form action="{% url 'orders:order' id=product.id %}" method="POST">
                                                    {% csrf_token %}
                                                    <input type="hidden" value="{{ product.id }}" name="id">
                                                    <button class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
    {#										    <a href="{% url 'orders:order' id=product.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>#}
                                                </form>
                                            {% else %}
                                                <a href="{% url 'accounts:login' %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Log In to buy</a>
                                            {% endif %}
                                        {% elif product.quantity == 0 %}
                                            <a href="" class="btn btn-danger" style="margin-bottom: 24px; border-radius: 0;" disabled=""><i class="fa fa-shopping-cart" style="margin-right: 5px;"></i>Out Of Stock</a>
                                        {% endif %}
									</div>
{#									<div class="product-overlay">#}
{#										<div class="overlay-content">#}
{#											<h2>&#36;{{ product.price }}</h2>#}
{#                                            <h3 style="color: #fff;">{{ ((100 * product.discount) / product.price) | int}} &#37; OFF</h3>#}
{#											<p style="max-width: 252px; overflow: hidden;">{{ product.product_name | truncate(30) }}</p>#}
{#											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>#}
{#										</div>#}
{#									</div>#}
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
{#										<li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>#}
									</ul>
								</div>
							</div>
						</div>
                        {% endfor %}


					</div><!--features_items-->

				</div>
			</div>
		</div>
	</section>
{% endblock %}

products/templates/products/review_update_form.html
<br>
<form action="{% url 'reviews:update' id=product.id %}" method="POST" class="form-group">
    {% csrf_token %}
    <textarea name="review" cols="102" rows="6">{{ review.review }}</textarea>
    <br>
    <b>Rate: </b> &emsp;
    <select name="rate" style="width: 80px;" class="btn btn-default dropdown-toggle">
        <option {% if review.rate == 5 %} selected {% endif %} value="5">5</option>
        <option {% if review.rate == 4 %} selected {% endif %} value="4">4</option>
        <option {% if review.rate == 3 %} selected {% endif %} value="3">3</option>
        <option {% if review.rate == 2 %} selected {% endif %} value="2">2</option>
        <option {% if review.rate == 1 %} selected {% endif %} value="1">1</option>
    </select>
    <br>
    <br>
    <button type="submit" class="btn btn-primary pull-left update">
        Update Review
    </button>
</form>